#!/usr/bin/env python3
"""Start a project whose first section is the gate, and which is empty on purpose.

    groundwork init                 # in the project directory
    groundwork init --name "..."    # with a title

It creates the directories the rest of the pipeline writes into, and one
document whose first section is the four measurements. That section is left
empty, because an empty gate section is the signal that work has not started -
and a project document whose first page is a plan rather than a measurement is
how a closed ceiling goes unnoticed until session ten.
"""
from __future__ import annotations

import argparse
import datetime
import os
import sys

DIRS = ["prereg", "results", "archive", "figures"]

PROJECT = """# {name}

> Started {date}. **Nothing below the gate may be worked on while the gate is empty.**

## 1. The gate — four measurements, on one split, before anything

Fill these in from measurements, not estimates, then run:

```bash
groundwork gate --baseline <strongest trivial, TUNED> --oracle <perfect access> \\
                --se <standard error of a difference> --random <shuffled arm> \\
                --positive-control <recovers a known effect> --positive-control-floor <its floor>
```

| | value | how it was measured |
|---|---|---|
| strongest trivial baseline, tuned as hard as the proposal | | |
| oracle — perfect access to the quantity the proposal estimates | | |
| standard error of a difference on this split | | |
| random or shuffled arm | | |
| positive control, and the floor it must clear | | |

**Verdict:** _(paste the gate's output; a NO-GO goes into `archive/` and the
project ends here)_

## 2. Is it occupied, and does it reduce?

```bash
groundwork lit occupancy "the mechanism, in three to five keywords"
```

- closest prior work, **read** rather than skimmed:
- can the quantity be written in a simpler equivalent form, and does that form
  already have a name:
- our own prior output, searched:

## 3. Which two deep areas is this a bridge between?

_(One deep area plus an application field is a deep-by-shallow project. That is
not a refusal — it changes what to defend and who to bring in. Name the
collaborator who is deep in the second area.)_

## 4. The claim, the null, and the venue

| | |
|---|---|
| the single sentence the result would support | |
| the result that would **end** this project | |
| who publishes that sentence, as written | |

## 5. Pre-registration

```bash
groundwork prereg new prereg/PREREG_run1.md --title "run 1"
groundwork prereg seal prereg/PREREG_run1.md
git add prereg/ && git commit -m "Pre-register run 1"   # BEFORE the run
```

## 6. What died

Every dead end goes in `archive/` with its cause, so it stays dead:

```bash
groundwork ledger kill --id <slug> --cause <from the taxonomy> \\
    --what "..." --settled-by "..." --reopen-if "..."
groundwork ledger roll
```
"""

GITIGNORE = """# generated by `groundwork init`
__pycache__/
*.pyc
# Raw model output is usually too large for a repository and is not the result.
# What must be committed is the per-item scored table, which is what makes every
# number in a write-up recomputable by a reader.
generations*.jsonl
scored*/
"""


def main(argv=None):
    ap = argparse.ArgumentParser(prog="groundwork init")
    ap.add_argument("--name", default="A research project")
    ap.add_argument("--dir", default=".")
    ap.add_argument("--force", action="store_true")
    a = ap.parse_args(argv)

    root = os.path.abspath(a.dir)
    made = []
    for d in DIRS:
        p = os.path.join(root, d)
        if not os.path.isdir(p):
            os.makedirs(p)
            made.append(d + "/")

    doc = os.path.join(root, "PROJECT.md")
    if os.path.exists(doc) and not a.force:
        print(f"{doc} exists; pass --force to overwrite")
        return 1
    with open(doc, "w", encoding="utf-8") as fh:
        fh.write(PROJECT.format(name=a.name,
                                date=datetime.date.today().isoformat()))
    made.append("PROJECT.md")

    gi = os.path.join(root, ".gitignore")
    if not os.path.exists(gi):
        with open(gi, "w", encoding="utf-8") as fh:
            fh.write(GITIGNORE)
        made.append(".gitignore")

    print("created: " + ", ".join(made))
    print()
    print("PROJECT.md's first section is the gate and it is empty. Fill it from")
    print("measurements before writing anything else - the cheapest thing that can")
    print("end a project should be the first thing that runs, and in one recorded")
    print("case it was run in session ten and had been closed the whole time.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
